### ISSUE TITLE
Update READMEs for beta release

### ISSUE THREAD

**Issue by dylans** [dojo/meta#140]
Update the READMEs for end-user instructions (npm install ... ) for the beta release, and follow the pattern in general from the @dojo/widgets README.

- [x] [@dojo/has](https://github.com/dojo/has)
- [x] [@dojo/shim](https://github.com/dojo/shim)
- [x] [@dojo/streams](https://github.com/dojo/streams)
- [x] [@dojo/core](https://github.com/dojo/core)
- [x] [@dojo/compose](https://github.com/dojo/compose)
- [x] [@dojo/widget-core](https://github.com/dojo/widget-core)
- [x] [@dojo/widgets](https://github.com/dojo/widgets)
- [x] [@dojo/routing](https://github.com/dojo/routing)
- [x] [@dojo/cli](https://github.com/dojo/cli)
- [x] [@dojo/cli-build](https://github.com/dojo/cli-build)
- [x] [@dojo/cli-create-app](https://github.com/dojo/cli-create-app)
- [x] [@dojo/loader](https://github.com/dojo/loader)
- [x] [@dojo/examples](https://github.com/dojo/examples)
- [x] [@dojo/interfaces](https://github.com/dojo/interfaces)
- [x] [@dojo/stores](https://github.com/dojo/stores)
- [x] [@dojo/i18n](https://github.com/dojo/i18n)

Please verify copyright (copyright symbol and JS Foundation) and license info, and beta description

**Comment by rorticus** [comment]
This shouldn't be closed...

**Comment by rorticus** [comment]
OK, I think all README updates are in PR.

**Comment by rorticus** [comment]
All updated!
