### ISSUE TITLE
Remove @dojo/interfaces

### ISSUE THREAD

**Issue by matt-gadd** [dojo/meta#223]
Given `@dojo/interfaces` is now pretty much redundant, we can get rid of it out of our downstream dependencies. To do this for non-cli packages, we simply need to add the remaining stray loader types to `@dojo/core` (PR here: https://github.com/dojo/core/pull/375). We should then be able to remove the dependency on `@dojo/interfaces` from all of the following:

- [x] [`dojo/core`](https://github.com/dojo/core)
- [x] [`dojo/examples`](https://github.com/dojo/examples)
- [x] [`dojo/i18n`](https://github.com/dojo/i18n)
- [x] [`dojo/interop`](https://github.com/dojo/interop)
- [x] [`dojo/routing`](https://github.com/dojo/routing)
- [x] [`dojo/stores`](https://github.com/dojo/stores)
- [x] [`dojo/streams`](https://github.com/dojo/streams)
- [x] [`dojo/widget-core`](https://github.com/dojo/widget-core)
- [x] [`dojo/widgets`](https://github.com/dojo/widgets)
- [x] [`dojo/test-extras`](https://github.com/dojo/test-extras)
- [x] [`dojo/web-editor`](https://github.com/dojo/web-editor)

After the above, the cli commands currently have a dependency on `@dojo/interfaces` for the cli typings, if we remove the current circular dependency issue due to bundling `@dojo/cli-create-app` with `@dojo/cli` (issue here: https://github.com/dojo/cli/issues/183), we can go ahead and just move these types back into `@dojo/cli` and make the packages below just rely on `@dojo/cli` as a dev dep for the typings.

- [ ] [`dojo/cli-build`](https://github.com/dojo/cli-build)
- [ ] [`dojo/cli-create-app`](https://github.com/dojo/cli-create-app)
- [ ] [`dojo/cli-create-widget`](https://github.com/dojo/cli-create-widget)
- [ ] [`dojo/cli-export-project`](https://github.com/dojo/cli-export-project)
- [ ] [`dojo/cli-test-intern`](https://github.com/dojo/cli-test-intern)
- [ ] [`dojo/cli-build-app`](https://github.com/dojo/cli-build-app)
- [ ] [`dojo/cli-create-theme`](https://github.com/dojo/cli-create-theme)

After the above, we can go ahead and remove/deprecate the `@dojo/interfaces` package and repo.

**Comment by umaar** [comment]
The pull requests are ready! When `"@dojo/cli": "~0.4.2"` is published then we can merge them
