### ISSUE TITLE
New TypeScript 2.0 Features

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#37]
The [TypeScript Roadmap for 2.0](https://github.com/Microsoft/TypeScript/wiki/Roadmap#20) list the major changes for TypeScript 2.0.  Most of these are available in `typescript@next`.  Features that I think that are important to us (e.g. we would want to adopt them quickly):

- [ ] `readonly` interfaces [Microsoft/TypeScript#6532](https://github.com/Microsoft/TypeScript/issues/6532)
- [ ] Specifying `this` type for functions [Microsoft/TypeScript#3694](https://github.com/Microsoft/TypeScript/issues/3694)
- [ ] ~~`async`/`await` for ES5 [Microsoft/TypeScript#1564](https://github.com/Microsoft/TypeScript/issues/1564)~~
- [ ] Non-nullable types [Microsoft/TypeScript#7140](https://github.com/Microsoft/TypeScript/issues/7140)

There maybe more...

**Comment by kitsonk** [comment]
* [ ] - We can now properly model load plugins, because TypeScript will allow us to to declare module IDs with wildcards (see: [Microsoft/TypeScript#6615](https://github.com/Microsoft/TypeScript/issues/6615))

**Comment by kitsonk** [comment]
These have been addressed as individual issues during the migration to TypeScript 2.0.
